import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'EN' | 'RU';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  EN: {
    'settings.title': 'Settings',
    'settings.general': 'General',
    'settings.integrations': 'Integrations',
    'settings.bots': 'My Bots',
    'settings.users': 'User Management',
    'settings.connection': 'Connection',
    'settings.connectionDesc': 'Configure your connection to the VibeMind server for synchronization and AI features.',
    'settings.language': 'Language',
    'settings.proxy': 'Network Proxy',
    'settings.webhooks': 'Home Automation (Webhooks)',
    'settings.export': 'Export & Backup',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.systemStatus': 'System Status',
    'settings.aiAssistant': 'AI Assistant',
    'settings.connected': 'Connected',
    'settings.notConfigured': 'Not Configured',
    'settings.telegramBot': 'Telegram Bot',
    'settings.live': 'Live',
    'settings.offline': 'Offline',
    'settings.proxyStatus': 'Proxy',
    'settings.configured': 'Configured',
    'settings.direct': 'Direct',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.dataManagement': 'Data Management',
    'settings.reindexSearch': 'Re-index AI Search',
    'settings.reindexDesc': 'Force regenerate all AI embeddings for your notes',
    'settings.reindexing': 'Re-indexing...',
    'settings.reindex': 'Re-index',
    'settings.markdownExport': 'Markdown Export',
    'settings.exportDesc': 'Download all notes as a ZIP archive',
    'settings.exportZip': 'Export ZIP',
    'settings.importNotes': 'Import Notes',
    'settings.importDesc': 'Import notes from a ZIP archive containing Markdown files',
    'settings.importZip': 'Import ZIP',
    'settings.importSuccess': 'Successfully imported notes!',
    'settings.importFailed': 'Failed to import notes.',
    'settings.llmProviders': 'LLM Providers',
    'settings.addProvider': 'Add Provider',
    'settings.active': 'Active',
    'settings.providerType': 'Provider Type',
    'settings.label': 'Label',
    'settings.modelName': 'Model Name',
    'settings.baseUrl': 'Base URL (OpenAI/Ollama only)',
    'settings.apiKey': 'API Key (Encrypted in DB)',
    'settings.status': 'Status:',
    'settings.notTested': 'Not Tested',
    'settings.error': 'Error',
    'settings.testConnection': 'Test Connection',
    'settings.testing': 'Testing...',
    'settings.externalDatabases': 'External Databases',
    'settings.externalDbDesc': 'Your system database is managed automatically. Add external DBs here to index them for AI RAG analysis.',
    'settings.addDb': 'Add DB',
    'settings.noExternalDbs': 'No external databases connected.',
    'settings.botConfig': 'Telegram Bot Configuration',
    'settings.botToken': 'Bot Token',
    'settings.adminId': 'Admin Telegram ID',
    'settings.allBots': 'All User Bots',
    'settings.adminIdDesc': 'Only this user will be able to interact with the bot.',
    'settings.admin': 'Admin',
    'settings.user': 'User',
    'settings.profile': 'Profile',
    'settings.logs': 'Logs',
    'settings.username': 'Username',
    'settings.email': 'Email',
    'settings.role': 'Role',
    'settings.actions': 'Actions',
    'settings.loadingUsers': 'Loading users...',
    'settings.noUsersFound': 'No users found.',
    'settings.serverReachable': 'Server is reachable',
    'settings.loginFailed': 'Login failed',
    'settings.checkServer': 'Checking server...',
    'settings.newPassword': 'New Password',
    'settings.updatePassword': 'Update Password',
    'settings.passwordUpdated': 'Password updated successfully',
    'settings.passwordUpdateFailed': 'Failed to update password',
    'settings.noLogs': 'No logs available',
    'settings.disconnected': 'Disconnected',
    'settings.proxySettings': 'Proxy Settings',
    'settings.proxyHost': 'Proxy Host',
    'settings.proxyPort': 'Proxy Port',
    'settings.testBot': 'Test Bot',
    'settings.testProxy': 'Test Proxy',
    'settings.proxyProtocol': 'Proxy Protocol',
    'settings.protocol': 'Protocol',
    'settings.host': 'Host',
    'settings.port': 'Port',
    'settings.usernameOptional': 'Username (Optional)',
    'settings.passwordOptional': 'Password (Optional)',
    'settings.userManagement': 'User Management',
    'settings.addUser': 'Add User',
    'settings.action': 'Action',
    'settings.noUsers': 'No users found. (Mock mode active)',
    'settings.saved': 'Settings saved! The backend bot is restarting with the new configuration.',
    'settings.saveFailed': 'Failed to save settings to the backend.',
    'settings.connSuccess': '✅ Connection Successful!',
    'settings.connFailed': '❌ Failed: ',
    'settings.apiFailed': 'Failed to connect to VibeMind API.',
    'settings.proxyHostReq': 'Please enter a proxy host first.',
    'settings.proxySuccess': '✅ Proxy connection successful!',
    'settings.proxyFailed': '❌ Proxy test failed: ',
    'settings.proxyReqFailed': '❌ Proxy test request failed.',
    'settings.proxyLocalMsg': 'Proxy settings saved locally. Full testing requires a server connection.',
    'settings.dbSuccess': 'External Database connected successfully!',
    'settings.dbFailed': 'Failed to connect external database.',
    'settings.dbError': 'Error connecting to external database.',
    'settings.reindexSuccess': 'Re-indexing complete!',
    'settings.reindexFailed': 'Failed to re-index notes. Check console for details.',
    'settings.exportFailed': 'Failed to export notes.',
    'settings.exportError': 'Error exporting notes.',
    'settings.optOpenAI': 'OpenAI / Compatible',
    'settings.optGemini': 'Google Gemini',
    'settings.optOpenRouter': 'OpenRouter',
    'settings.optOllama': 'Ollama (Local)',
    'settings.phDeepSeek': 'e.g., DeepSeek, Groq, Local',
    'settings.phModel': 'e.g., gpt-4o-mini',
    'settings.phAdminId': 'e.g., 12345678',
    'settings.sync': 'Synchronization',
    'settings.enterUrl': 'Please enter server URL first.',
    'settings.serverUrl': 'Server URL',
    'settings.syncLogin': 'Login',
    'settings.syncPassword': 'Password',
    'settings.syncStatus': 'Sync Status',
    'settings.syncIdle': 'Idle',
    'settings.syncing': 'Syncing...',
    'settings.syncError': 'Sync Error',
    'settings.syncSuccess': 'Sync Complete',
    'settings.syncNow': 'Sync Now',
    'sync.syncing': 'Syncing...',
    'sync.error': 'Sync Error',
    'sync.success': 'Sync Complete',
    'sidebar.newNote': 'New Note',
    'sidebar.newFolder': 'New Folder',
    'sidebar.search': 'Search',
    'sidebar.searchPlaceholder': 'Search notes...',
    'sidebar.settings': 'Settings',
    'sidebar.rename': 'Rename',
    'sidebar.delete': 'Delete',
    'sidebar.share': 'Share',
    'sidebar.pin': 'Pin',
    'sidebar.unpin': 'Unpin',
    'sidebar.moveTo': 'Move to...',
    'sidebar.root': 'Root (Workspace)',
    'sidebar.moveNoteTitle': 'Move Note',
    'sidebar.cancel': 'Cancel',
    'sidebar.logout': 'Logout',
    'sidebar.owner': 'Owner',
    'editor.summarize': 'Summarize',
    'editor.emptyTitle': 'Your notes, beautifully',
    'editor.empty': 'Select a note or create a new one',
    'editor.noteTitlePlaceholder': 'Note Title',
    'editor.syncing': 'Syncing',
    'editor.saved': 'Saved',
    'editor.relatedNotes': 'Related Notes',
    'editor.linkToNote': 'Link to note',
    'editor.create': 'Create',
    'editor.startWriting': 'Start writing...',
    'editor.plainText': 'Plain Text',
    'chat.placeholder': 'Ask your notes...',
    'chat.welcome': 'I am VibeMind AI. I have indexed your notes. What would you like to know?',
    'chat.backlinks': 'Backlinks',
    'chat.outgoingLinks': 'Outgoing Links',
    'chat.noBacklinks': 'No backlinks found for this note.',
    'chat.searching': '🔍 Searching for notes: «{query}»...',
    'share.titleNote': 'Share note',
    'share.titleFolder': 'Share folder',
    'share.description': 'Share with specific users or create a public link.',
    'share.specificUser': 'Specific User',
    'share.publicLink': 'Public Link',
    'share.targetUsername': 'Target username',
    'share.usernamePlaceholder': 'username',
    'share.access': 'Access',
    'share.read': 'Read',
    'share.write': 'Write',
    'share.grant': 'Grant',
    'share.createLink': 'Create Link',
    'share.copyLink': 'Copy link',
    'share.loading': 'Loading shares...',
    'share.noShares': 'No shares exist for this resource yet.',
    'folder.setPassword': 'Set Password',
    'folder.changePassword': 'Change Password',
    'folder.removePassword': 'Remove Password',
    'folder.enterPassword': 'Enter Password',
    'folder.password': 'Password',
    'folder.confirmPassword': 'Confirm Password',
    'folder.passwordRequired': 'Password is required',
    'folder.passwordsMismatch': 'Passwords do not match',
    'folder.wrongPassword': 'Wrong password',
    'folder.unlock': 'Unlock',
    'folder.setDesc': 'Protect this folder with a password.',
    'folder.verifyDesc': 'This folder is protected.',
    'folder.confirmSet': 'Set Password',
    'folder.oldPassword': 'Old Password',
    'folder.oldPasswordRequired': 'Old password is required',
    'folder.confirmChange': 'Change Password',
    'folder.setupError': 'Failed to set password',
    'folder.removeError': 'Failed to remove password',
    'folder.error': 'An error occurred',
    'common.untitled': 'Untitled',
    'common.newNote': 'New Note',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.save': 'Save',
    'common.close': 'Close',
    'app.editMode': 'Edit Mode',
    'app.previewMode': 'Preview Mode',
    'app.graphView': 'Graph View',
    'sidebar.personalWorkspace': 'Personal workspace',
    'sidebar.recent': 'Recent',
    'sidebar.smartFolders': 'Smart',
    'smart.recentWeek': 'Last 7 days',
    'smart.withTags': 'With tags',
    'smart.withImages': 'With images',
    'smart.withTasks': 'With tasks',
    'smart.noTags': 'No tags',
    'sidebar.favorites': 'Favorites',
    'sidebar.folders': 'Folders',
    'chat.assistant': 'Assistant',
    'chat.noOutgoingLinks': 'No outgoing links found.',
    'editor.bold': 'Bold',
    'editor.italic': 'Italic',
    'editor.link': 'Link',
    'editor.image': 'Image',
    'editor.numberedList': 'Numbered List',
    'editor.list': 'List',
    'editor.codeBlock': 'Code Block',
    'editor.wikilink': 'Wikilink',
    'editor.table': 'Table',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'app.stats': 'Statistics',
    'app.bento': 'Bento Grid',
    'bento.title': 'Everything, beautifully',
    'bento.notes': 'notes',
    'bento.note': 'Note',
    'table.noTable': 'No table found in this note',
    'table.addRow': 'Add Row',
    'table.filter': 'Filter...',
    'table.total': 'Total',
    'table.rows': 'rows',
    'table.filtered': 'Showing',
    'graph.filterTags': 'Filter by tag',
    'graph.notes': 'notes',
    'app.calendar': 'Calendar',
    'stats.title': 'Statistics',
    'stats.totalNotes': 'Total Notes',
    'stats.totalWords': 'Total Words',
    'stats.totalLinks': 'Total Links',
    'stats.totalTags': 'Total Tags',
    'stats.topTags': 'Top Tags',
    'calendar.title': 'Calendar',
    'login.secure': 'Secure connection established',
    'modal.createFolder': 'Create New Folder',
    'modal.createNestedFolder': 'Create Nested Folder',
    'modal.folderName': 'Folder Name',
    'modal.createUser': 'Create User',
    'modal.editUser': 'Edit User',
    'modal.addUser': 'Add User',
    'modal.saveChanges': 'Save Changes',
    'modal.addDatabase': 'Add Database',
  },
  RU: {
    'settings.title': 'Настройки',
    'settings.general': 'Общие',
    'settings.integrations': 'Интеграции',
    'settings.bots': 'Мои боты',
    'settings.users': 'Пользователи',
    'settings.connection': 'Подключение',
    'settings.connectionDesc': 'Настройте подключение к серверу VibeMind для синхронизации и функций ИИ.',
    'settings.language': 'Язык',
    'settings.proxy': 'Сетевой прокси',
    'settings.webhooks': 'Умный дом (Webhooks)',
    'settings.export': 'Экспорт и резервное копирование',
    'settings.save': 'Сохранить',
    'settings.saving': 'Сохранение...',
    'settings.systemStatus': 'Статус системы',
    'settings.aiAssistant': 'ИИ Ассистент',
    'settings.connected': 'Подключен',
    'settings.notConfigured': 'Не настроен',
    'settings.telegramBot': 'Telegram Бот',
    'settings.live': 'Онлайн',
    'settings.offline': 'Офлайн',
    'settings.proxyStatus': 'Прокси',
    'settings.configured': 'Настроен',
    'settings.direct': 'Напрямую',
    'settings.theme': 'Тема',
    'settings.light': 'Светлая',
    'settings.dark': 'Темная',
    'settings.dataManagement': 'Управление данными',
    'settings.reindexSearch': 'Переиндексация ИИ',
    'settings.reindexDesc': 'Принудительно пересоздать все векторные представления для заметок',
    'settings.reindexing': 'Индексация...',
    'settings.reindex': 'Переиндексировать',
    'settings.markdownExport': 'Экспорт в Markdown',
    'settings.exportDesc': 'Скачать все заметки в виде ZIP-архива',
    'settings.exportZip': 'Экспорт ZIP',
    'settings.importNotes': 'Импорт заметок',
    'settings.importDesc': 'Импорт заметок из ZIP-архива с Markdown файлами',
    'settings.importZip': 'Импорт ZIP',
    'settings.importSuccess': 'Заметки успешно импортированы!',
    'settings.importFailed': 'Не удалось импортировать заметки.',
    'settings.llmProviders': 'Провайдеры ИИ',
    'settings.addProvider': 'Добавить провайдера',
    'settings.active': 'Активен',
    'settings.providerType': 'Тип провайдера',
    'settings.label': 'Название',
    'settings.modelName': 'Имя модели',
    'settings.baseUrl': 'Базовый URL (только OpenAI/Ollama)',
    'settings.apiKey': 'API Ключ (шифруется в БД)',
    'settings.status': 'Статус:',
    'settings.notTested': 'Не проверен',
    'settings.error': 'Ошибка',
    'settings.testConnection': 'Проверить подключение',
    'settings.testing': 'Проверка...',
    'settings.externalDatabases': 'Внешние базы данных',
    'settings.externalDbDesc': 'Системная БД управляется автоматически. Добавьте внешние БД для их индексации ИИ.',
    'settings.addDb': 'Добавить БД',
    'settings.noExternalDbs': 'Нет подключенных внешних баз данных.',
    'settings.botConfig': 'Конфигурация Telegram Бота',
    'settings.botToken': 'Токен бота',
    'settings.adminId': 'Telegram ID администратора',
    'settings.allBots': 'Боты всех пользователей',
    'settings.adminIdDesc': 'Только этот пользователь сможет общаться с ботом.',
    'settings.admin': 'Администратор',
    'settings.user': 'Пользователь',
    'settings.profile': 'Профиль',
    'settings.logs': 'Логи',
    'settings.username': 'Имя пользователя',
    'settings.email': 'Email',
    'settings.role': 'Роль',
    'settings.actions': 'Действия',
    'settings.loadingUsers': 'Загрузка пользователей...',
    'settings.noUsersFound': 'Пользователи не найдены.',
    'settings.serverReachable': 'Сервер доступен',
    'settings.loginFailed': 'Ошибка входа',
    'settings.checkServer': 'Проверка сервера...',
    'settings.newPassword': 'Новый пароль',
    'settings.updatePassword': 'Обновить пароль',
    'settings.passwordUpdated': 'Пароль успешно обновлен',
    'settings.passwordUpdateFailed': 'Не удалось обновить пароль',
    'settings.noLogs': 'Логи отсутствуют',
    'settings.disconnected': 'Отключен',
    'settings.proxySettings': 'Настройки прокси',
    'settings.proxyHost': 'Хост прокси',
    'settings.proxyPort': 'Порт прокси',
    'settings.testBot': 'Проверить бота',
    'settings.testProxy': 'Проверить прокси',
    'settings.proxyProtocol': 'Протокол прокси',
    'settings.protocol': 'Протокол',
    'settings.host': 'Хост',
    'settings.port': 'Порт',
    'settings.usernameOptional': 'Имя пользователя (опционально)',
    'settings.passwordOptional': 'Пароль (опционально)',
    'settings.userManagement': 'Управление пользователями',
    'settings.addUser': 'Добавить пользователя',
    'settings.action': 'Действия',
    'settings.noUsers': 'Пользователи не найдены.',
    'settings.saved': 'Настройки сохранены! Бот перезапускается с новой конфигурацией.',
    'settings.saveFailed': 'Не удалось сохранить настройки.',
    'settings.connSuccess': '✅ Подключение успешно!',
    'settings.connFailed': '❌ Ошибка: ',
    'settings.apiFailed': 'Не удалось подключиться к VibeMind API.',
    'settings.proxyHostReq': 'Пожалуйста, введите хост прокси.',
    'settings.proxySuccess': '✅ Подключение к прокси успешно!',
    'settings.proxyFailed': '❌ Ошибка проверки прокси: ',
    'settings.proxyReqFailed': '❌ Ошибка запроса проверки прокси.',
    'settings.proxyLocalMsg': 'Настройки прокси сохранены локально. Полноценная проверка возможна только через сервер.',
    'settings.dbSuccess': 'Внешняя БД успешно подключена!',
    'settings.dbFailed': 'Не удалось подключить внешнюю БД.',
    'settings.dbError': 'Ошибка при подключении внешней БД.',
    'settings.reindexSuccess': 'Переиндексация завершена!',
    'settings.reindexFailed': 'Не удалось переиндексировать заметки. Проверьте консоль.',
    'settings.exportFailed': 'Не удалось экспортировать заметки.',
    'settings.exportError': 'Ошибка при экспорте заметок.',
    'settings.optOpenAI': 'OpenAI / Совместимые',
    'settings.optGemini': 'Google Gemini',
    'settings.optOpenRouter': 'OpenRouter',
    'settings.optOllama': 'Ollama (Локально)',
    'settings.phDeepSeek': 'напр., DeepSeek, Groq, Local',
    'settings.phModel': 'напр., gpt-4o-mini',
    'settings.phAdminId': 'напр., 12345678',
    'settings.sync': 'Синхронизация',
    'settings.enterUrl': 'Пожалуйста, сначала введите URL сервера.',
    'settings.serverUrl': 'URL сервера',
    'settings.syncLogin': 'Логин',
    'settings.syncPassword': 'Пароль',
    'settings.syncStatus': 'Статус синхронизации',
    'settings.syncIdle': 'Ожидание',
    'settings.syncing': 'Синхронизация...',
    'settings.syncError': 'Ошибка синхронизации',
    'settings.syncSuccess': 'Синхронизация завершена',
    'settings.syncNow': 'Синхронизировать сейчас',
    'sync.syncing': 'Синхронизация...',
    'sync.error': 'Ошибка синхронизации',
    'sync.success': 'Синхронизация завершена',
    'sidebar.newNote': 'Новая заметка',
    'sidebar.newFolder': 'Новая папка',
    'sidebar.search': 'Поиск',
    'sidebar.searchPlaceholder': 'Поиск заметок...',
    'sidebar.settings': 'Настройки',
    'sidebar.rename': 'Переименовать',
    'sidebar.delete': 'Удалить',
    'sidebar.share': 'Поделиться',
    'sidebar.pin': 'Закрепить',
    'sidebar.unpin': 'Открепить',
    'sidebar.moveTo': 'Переместить в...',
    'sidebar.root': 'Корень (Рабочая область)',
    'sidebar.moveNoteTitle': 'Переместить заметку',
    'sidebar.cancel': 'Отмена',
    'sidebar.logout': 'Выйти',
    'sidebar.owner': 'Владелец',
    'editor.summarize': 'Суммаризировать',
    'editor.emptyTitle': 'Ваши заметки',
    'editor.empty': 'Выберите заметку или создайте новую',
    'editor.noteTitlePlaceholder': 'Заголовок заметки',
    'editor.syncing': 'Синхронизация',
    'editor.saved': 'Сохранено',
    'editor.relatedNotes': 'Похожие заметки',
    'editor.linkToNote': 'Ссылка на заметку',
    'editor.create': 'Создать',
    'editor.startWriting': 'Начните писать...',
    'editor.plainText': 'Простой текст',
    'chat.placeholder': 'Спросите свои заметки...',
    'chat.welcome': 'Я VibeMind AI. Я проиндексировал ваши заметки. Что вы хотите узнать?',
    'chat.backlinks': 'Обратные ссылки',
    'chat.outgoingLinks': 'Исходящие ссылки',
    'chat.noBacklinks': 'Обратных ссылок не найдено.',
    'chat.searching': '🔍 Ищу заметки по запросу: «{query}»...',
    'share.titleNote': 'Поделиться заметкой',
    'share.titleFolder': 'Поделиться папкой',
    'share.description': 'Поделитесь с конкретными пользователями или создайте публичную ссылку.',
    'share.specificUser': 'Конкретный пользователь',
    'share.publicLink': 'Публичная ссылка',
    'share.targetUsername': 'Имя пользователя',
    'share.usernamePlaceholder': 'имя пользователя',
    'share.access': 'Доступ',
    'share.read': 'Чтение',
    'share.write': 'Запись',
    'share.grant': 'Предоставить',
    'share.createLink': 'Создать ссылку',
    'share.copyLink': 'Копировать ссылку',
    'share.loading': 'Загрузка доступов...',
    'share.noShares': 'Доступы для этого ресурса еще не созданы.',
    'folder.setPassword': 'Запоролить папку',
    'folder.changePassword': 'Сменить пароль',
    'folder.removePassword': 'Удалить пароль',
    'folder.enterPassword': 'Введите пароль',
    'folder.password': 'Пароль',
    'folder.confirmPassword': 'Подтвердите пароль',
    'folder.passwordRequired': 'Пароль обязателен',
    'folder.passwordsMismatch': 'Пароли не совпадают',
    'folder.wrongPassword': 'Неверный пароль',
    'folder.unlock': 'Разблокировать',
    'folder.setDesc': 'Защитите эту папку паролем.',
    'folder.verifyDesc': 'Эта папка защищена паролем.',
    'folder.confirmSet': 'Установить пароль',
    'folder.oldPassword': 'Старый пароль',
    'folder.oldPasswordRequired': 'Старый пароль обязателен',
    'folder.confirmChange': 'Сменить пароль',
    'folder.setupError': 'Не удалось установить пароль',
    'folder.removeError': 'Не удалось удалить пароль',
    'folder.error': 'Произошла ошибка',
    'common.untitled': 'Без названия',
    'common.newNote': 'Новая заметка',
    'common.cancel': 'Отмена',
    'common.create': 'Создать',
    'common.save': 'Сохранить',
    'common.close': 'Закрыть',
    'app.editMode': 'Режим редактирования',
    'app.previewMode': 'Режим просмотра',
    'app.graphView': 'Граф связей',
    'sidebar.personalWorkspace': 'Личное пространство',
    'sidebar.recent': 'Недавние',
    'sidebar.smartFolders': 'Умные',
    'smart.recentWeek': 'Последние 7 дней',
    'smart.withTags': 'С тегами',
    'smart.withImages': 'С изображениями',
    'smart.withTasks': 'С задачами',
    'smart.noTags': 'Без тегов',
    'sidebar.favorites': 'Избранное',
    'sidebar.folders': 'Папки',
    'chat.assistant': 'Ассистент',
    'chat.noOutgoingLinks': 'Исходящих ссылок не найдено.',
    'editor.bold': 'Жирный',
    'editor.italic': 'Курсив',
    'editor.link': 'Ссылка',
    'editor.image': 'Изображение',
    'editor.numberedList': 'Нумерованный список',
    'editor.list': 'Список',
    'editor.codeBlock': 'Блок кода',
    'editor.wikilink': 'Wikilink',
    'editor.table': 'Таблица',
    'login.username': 'Имя пользователя',
    'login.password': 'Пароль',
    'login.signIn': 'Войти',
    'app.stats': 'Статистика',
    'app.bento': 'Bento сетка',
    'bento.title': 'Всё красиво',
    'bento.notes': 'заметок',
    'bento.note': 'Заметка',
    'table.noTable': 'Таблица не найдена',
    'table.addRow': 'Добавить строку',
    'table.filter': 'Фильтр...',
    'table.total': 'Всего',
    'table.rows': 'строк',
    'table.filtered': 'Показано',
    'graph.filterTags': 'Фильтр по тегу',
    'graph.notes': 'заметок',
    'app.calendar': 'Календарь',
    'stats.title': 'Статистика',
    'stats.totalNotes': 'Всего заметок',
    'stats.totalWords': 'Всего слов',
    'stats.totalLinks': 'Всего ссылок',
    'stats.totalTags': 'Всего тегов',
    'stats.topTags': 'Популярные теги',
    'calendar.title': 'Календарь',
    'login.secure': 'Безопасное соединение установлено',
    'modal.createFolder': 'Создать новую папку',
    'modal.createNestedFolder': 'Создать вложенную папку',
    'modal.folderName': 'Название папки',
    'modal.createUser': 'Создать пользователя',
    'modal.editUser': 'Редактировать пользователя',
    'modal.addUser': 'Добавить пользователя',
    'modal.saveChanges': 'Сохранить',
    'modal.addDatabase': 'Добавить базу данных',
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('app_language');
      return (saved as Language) || 'EN';
    } catch (e) {
      return 'EN';
    }
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    try {
      localStorage.setItem('app_language', lang);
    } catch (e) {}
  };

  const t = (key: string, params?: Record<string, string>) => {
    let translation = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        translation = translation.replace(`{${k}}`, v);
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
